[package]
name = "foss4g2025"
version = "0.1.0"
edition = "2024"
description = "Accelerating GeoTIFF readers with Rust."
readme = "README.md"
repository = "https://github.com/weiji14/foss4g2025"
license = "MPL-2.0"
rust-version = "1.89.0"
authors = ["Wei Ji <23487320+weiji14@users.noreply.github.com>"]

[dependencies]
cog3pio = { version = "0.0.1", git = "https://github.com/weiji14/cog3pio", features = [
    "cuda",
], rev = "1564f828bc759e1c8aa1a53eb3359aa2786b12a1", optional = true }
cudarc = { version = "0.17.7", features = [
    "cuda-version-from-build-system",
    "fallback-latest",
], optional = true }

[dev-dependencies]
async-tiff = { version = "0.1.0", git = "https://github.com/developmentseed/async-tiff", tag = "py-v0.2.0" }
bytes = "1.10.1"
criterion = { package = "codspeed-criterion-compat", version = "4.1.0" }
dlpark = { git = "https://github.com/SunDoge/dlpark.git", version = "0.6.0", features = [
    "ndarray",
], rev = "2455a562af10a6655465d24d7e9c78996c613e6a" }
gdal = { git = "https://github.com/georust/gdal.git", version = "0.18.0", features = [
    "array",
    "bindgen",
], rev = "3df2c28f8c83f80d209b34d46f30d6c35e803e07" }
ndarray = "0.16.1"
object_store = "0.12.4"
rayon = "1.11.0"
tokio = "1.48.0"
url = "2.5.7"

[features]
cuda = ["cudarc", "cog3pio"]

[[bench]]
name = "read_geotiff"
harness = false
