# Run performance benchmarks
name: Benchmarks

on:
  push:
    branches: ["main"]
  release:
    types: [published]
  pull_request:
    types: [opened, reopened, synchronize]
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  rust:
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/osgeo/gdal:ubuntu-small-3.12.0
    strategy:
      matrix:
        toolchain:
          - 1.85.0 # msrv
          - stable
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Download and process sample GeoTIFF
        run: |
          wget --directory-prefix=benches https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/37/M/BV/2024/10/S2A_37MBV_20241029_0_L2A/TCI.tif
          gdal raster convert --co COMPRESS=LZW --co TILED=YES --co PREDICTOR=2 benches/TCI.tif benches/TCI_lzw.tif
          ls -lh benches/

      - name: Setup rust toolchain, cache and cargo-codspeed binary
        uses: moonrepo/setup-rust@ede6de059f8046a5e236c94046823e2af11ca670 # v1.2.2
        with:
          channel: ${{ matrix.toolchain }}
          cache: false
          cache-target: release
          bins: cargo-codspeed

      - name: Build the benchmark target(s)
        run: cargo codspeed build

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@bb005fe1c1eea036d3894f02c049cb6b154a1c27 # v4.3.3
        with:
          mode: instrumentation
          run: cargo codspeed run
