name: CI

on:
  push:
    branches: ["main"]
  release:
    types: [published]
  pull_request:
    types: [opened, reopened, synchronize]
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  rust:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        toolchain:
          - 1.85.0 # msrv
          - stable
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Update Rust toolchain
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: Build
        run: cargo build --verbose --all-features
